# This is a "rank 1 array" 

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [7]:
print(type(a))

<class 'numpy.ndarray'>


### ^ Confirming list has been made into an array

In [8]:
print(a.shape)

(3,)


### The shape of an array is the number of elements in each dimension

In [10]:
print(a[0], a[1], a[2])

1 2 3


### Prints out elements in the array, just like in a list.

In [11]:
a[0]=4
print(a)

[4 2 3]


### Replacing the first element

---------------------------------------------------

# This is a "rank 2 array" . Its a "2 array" bc it has a column and rows(indexes), unlike "1 array" which only has columns.

In [13]:
b = np.array([[1,2,3], [4,5,6]])

In [14]:
print(b)

[[1 2 3]
 [4 5 6]]


### Pulling elements from array

In [20]:
print(b[0,0], b[1,1], b[0,2])

1 5 3


In [18]:
print(b.shape)

(2, 3)
